config/routes.rb
Rails.application.routes.draw do

  resources :chi_tiet_gio_hangs
  resources :gio_hangs
  resources :don_hangs
  devise_for :views
  devise_for :khach_hangs
  
  root 'trang_chu#index', as: 'home'

  get '/store' => 'hang_hoas#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy' 

  namespace :admin do
    resources :thong_kes, only: [:index]
    resources :don_hangs
    resources :khach_hangs
    resources :hang_hoas
    resources :danh_mucs
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end

  resources :hang_hoas, only: [:index, :show]
  resources :danh_mucs, only: [:index, :show]

end

app/models/don_hang.rb
class DonHang < ActiveRecord::Base

	belongs_to :khach_hang
	
	before_create :tong_cong, unless: :persisted?
	after_initialize :set_defaults, unless: :persisted?
	has_many :chi_tiet_gio_hangs, dependent: :destroy

	KIEU_THANH_TOAN = ["Chuyển khoản", "Thanh toán tại cửa hàng", "Thanh toán khi nhận hàng"]
	TINH_TRANG = [ "Đã tiếp nhận", "Đang xử lý", "Đã chuẩn bị xong", "Đang giao hàng", "Giao hàng thành công" ]

	validates :nguoi_nhan, :dia_chi, :email, presence: true
	validates :kieu_thanh_toan, inclusion: KIEU_THANH_TOAN

	def set_defaults
		self.tinh_trang ||= 'Đã tiếp nhận'
	end

	def them_chi_tiet_tu_gio_hang(gio_hang)
		gio_hang.chi_tiet_gio_hangs.each do |item|
			item.gio_hang_id = nil
			chi_tiet_gio_hangs << item
		end
	end

	def tong_cong
		self.tong_cong = chi_tiet_gio_hangs.to_a.sum {|chi_tiet| chi_tiet.tong_cong}
	end

	def self.doanh_thu_thang
		@don_hangs = DonHang.where('tinh_trang LIKE ?', 'Giao hàng thành công').group('month(updated_at)').order('updated_at desc')
		@doanh_thu_thang = @don_hangs.sum('tong_cong')
	end

	def self.doanh_thu_nam
		@don_hangs = DonHang.select('year(updated_at)').where('tinh_trang LIKE ?', 'Giao hàng thành công').group('year(updated_at)')
		@doanh_thu_nam = @don_hangs.sum('tong_cong')
	end

end

app/controllers/admin/don_hangs_controller.rb
class Admin::DonHangsController < Admin::ApplicationController

	include GioHangHienTai
	before_action :set_gio_hang, only: [:new, :create]
	before_action :set_don_hang, only: [:show, :edit, :update, :destroy]

	def index
		@don_hangs = DonHang.all
	end

	def show
		
	end

	def edit
	end

	def update
		if @don_hang.update(don_hang_params)
			redirect_to admin_don_hangs_url, notice: 'Cập nhật đơn hàng thành công'
		else
      		flash[:alert] = 'Có lỗi khi cập nhật đơn hàng'
      		render 'edit'
    end
	end

	def new
		if @gio_hang.chi_tiet_gio_hangs.empty?
			redirect_to store_url, notice: "Giỏ hàng của bạn chưa có sản phẩm nào"
			return
		end
		@don_hang = DonHang.new
	end


	def create
		@don_hang = DonHang.new(don_hang_params)
		@don_hang.them_chi_tiet_tu_gio_hang(@gio_hang)

		if @don_hang.save
			GioHang.destroy(session[:gio_hang_id])
			session[:gio_hang_id] = nil
		else
	        format.html { render action: 'new' }
	        format.json { render json: @order.errors, status: :unprocessable_entity }
      	end

	end

	private

	def set_don_hang
		@don_hang = DonHang.find(params[:id])
	end

	def don_hang_params
		params.require(:don_hang).permit(:nguoi_nhan, :dia_chi, :email, :tinh_trang, :thanh_toan, :kieu_thanh_toan)
	end

end

app/controllers/don_hangs_controller.rb
class DonHangsController < ApplicationController

	include GioHangHienTai
	before_action :set_gio_hang, only: [:index, :show, :new, :create]
	before_action :set_don_hang, only: [:show, :edit, :update, :destroy]

	def index
		@don_hangs = current_khach_hang.don_hangs
	end

	def show
	end

	def edit
	end

	def new
		if @gio_hang.chi_tiet_gio_hangs.empty?
			redirect_to store_url, notice: "Giỏ hàng của bạn chưa có sản phẩm nào"
			return
		end
		@khach_hang = current_khach_hang
		@don_hang = DonHang.new

	end


	def create
		@don_hang = DonHang.new(don_hang_params)
		@don_hang.them_chi_tiet_tu_gio_hang(@gio_hang)
		@don_hang.khach_hang_id = current_khach_hang.id
		@khach_hang = current_khach_hang

		if @don_hang.save
			GioHang.destroy(session[:gio_hang_id])
			session[:gio_hang_id] = nil
			redirect_to don_hang_url(@don_hang), notice: "Bạn đã đặt hàng thành công!"
		else
	        flash[:alert] = "Hãy điền thông tin đầy để chúng tôi có thể xử lý đơn hàng"
			render 'new'
      	end

	end

	private

	def set_don_hang
		@don_hang = DonHang.find(params[:id])
	end

	def don_hang_params
		params.require(:don_hang).permit(:nguoi_nhan, :dia_chi, :email, :tinh_trang, :thanh_toan, :kieu_thanh_toan)
	end

end

app/views/don_hangs/_form.html.erb
<%= form_for(@don_hang, html: { class: 'form-horizontal col-md-6 col-sm-offset-3' }) do |f| %>
<div id="error_explanation">
  <h2><% pluralize(@don_hang.errors.count, "error") %></h2>
  <ul>
    <% @don_hang.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<div class="form-group">
  <%= f.label 'Họ và tên', class: 'col-sm-4 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :nguoi_nhan, autofocus: true,  class: 'form-control', input_html: { value: @khach_hang.ten_kh } %>
  </div>
</div>
<div class="form-group">
  <%= f.label :email, class: 'col-sm-4 control-label' %>
  <div class="col-sm-8">
    <%= f.email_field :email, autofocus: true,  class: 'form-control', input_html: { value: :email } %>
  </div>
</div>
<div class="form-group">
  <%= f.label 'Địa chỉ', class: 'col-sm-4 control-label' %>
  <div class="col-sm-8">
    <%= f.text_field :dia_chi, autocomplete: "off", class: 'form-control', input_html: { value: :dia_chi } %>
  </div>
</div>
<div class="form-group">
  <%= f.label 'Điện thoại', class: "col-sm-4 control-label" %>
  <div class="col-sm-8">
    <%= f.text_field :sdt, autocomplete: "off", class: 'form-control', input_html: { value: :dien_thoai}%>
  </div>
</div>
<div class="form-group">
  <%= f.label 'Phương thức thanh toán', class: "col-sm-4 control-label" %>
  <div class="col-sm-8">
    <%= f.select :kieu_thanh_toan, DonHang::KIEU_THANH_TOAN, {prompt: 'Chọn phương thức thanh toán'}, {class: 'form-control'} %>
  </div>
</div>
<div class="col-sm-offset-4 col-sm-8" style="padding-left: 10px">
  <%= f.submit "Đặt hàng", class: 'btn btn-success'%>
</div>
<% end %>

app/views/don_hangs/index.html.erb
<div class="container">
	<h2>ĐƠN HÀNG CỦA TÔI</h2>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Mã đơn hàng</th>
				<th>Ngày đặt hàng</th>
				<th>Tổng tiền</th>
				<th>Trạng thái</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<% @don_hangs.each do |don_hang| %>
			<tr>
				<td><%= don_hang.id %></td>
				<td><%= don_hang.created_at %></td>
				<td><%= number_to_currency(don_hang.tong_cong, locale: :vn)%></td>
				<td><%= don_hang.tinh_trang %></td>
				<td><%= link_to 'Xem đơn hàng', don_hang_path(don_hang)%> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/don_hangs/new.html.erb
<div class="container">
  <fieldset>
    <legend>THÔNG TIN GIAO HÀNG</legend>
    <%= form_for(@don_hang, html: { class: 'form-horizontal col-md-6 col-sm-offset-3' }) do |f| %>
    <div id="error_explanation">
      <h2><% pluralize(@don_hang.errors.count, "error") %></h2>
      <ul>
        <% @don_hang.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% if khach_hang_signed_in? %>
    <div class="form-group">
      <%= f.label 'Họ và tên người nhận', class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :nguoi_nhan, value: current_khach_hang.ten_kh, autofocus: true,  class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.email_field :email, autocomplete: true,  class: 'form-control', value: current_khach_hang.email%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Địa chỉ', class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :dia_chi, autocomplete: "off", class: 'form-control', value: current_khach_hang.dia_chi%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Điện thoại', class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :sdt, autocomplete: "off", class: 'form-control', value: current_khach_hang.dien_thoai %>
      </div>
    </div>
    <% else %>
    <div class="form-group">
      <%= f.label 'Họ và tên người nhận', class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :nguoi_nhan, autofocus: true,  class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.email_field :email, autocomplete: true,  class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Địa chỉ', class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :dia_chi, autocomplete: "off", class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Điện thoại', class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= f.text_field :sdt, autocomplete: "off", class: 'form-control' %>
      </div>
    </div>
    <% end %>
    <div class="form-group">
      <%= f.label 'Phương thức thanh toán', class: "col-sm-4 control-label" %>
      <div class="col-sm-8">
        <%= f.select :kieu_thanh_toan, DonHang::KIEU_THANH_TOAN, {prompt: 'Chọn phương thức thanh toán'}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="col-sm-offset-4 col-sm-8" style="padding-left: 10px">
      <%= f.submit "Đặt hàng", class: 'btn btn-success'%>
    </div>
    <% end %>
  </fieldset>
</div>

app/views/don_hangs/show.html.erb
<div class="container">
	<h2>Chi tiết đơn hàng</h2>
	<div class="customer-info">
		<table class="table table-bordered">
			<tr>
				<th>Email</th>
				<td><%= @don_hang.khach_hang.email if @don_hang.khach_hang %></td>
			</tr>
			<tr>
				<th>Tên khách hàng</th>
				<td><%= @don_hang.khach_hang.ten_kh if @don_hang.khach_hang %></td>
			</tr>
			<tr>
				<th>Địa chỉ nhận hàng</th>
				<td><%= @don_hang.dia_chi %></td>
			</tr>
			<tr>
				<th>Điện thoại liên lạc</th>
				<td><%= @don_hang.sdt %></td>
			</tr>
			<tr>
				<th>Tên người nhận</th>
				<td><%= @don_hang.nguoi_nhan %></td>
			</tr>
			<tr>
				<th>Kiểu thanh toán</th>
				<td><%= @don_hang.kieu_thanh_toan %></td>
			</tr>
			<tr>
				<th>Đặt hàng lúc</th>
				<td><%= @don_hang.created_at %></td>
			</tr>
			<tr>
				<th>Giao hàng</th>
				<td><%= @don_hang.tinh_trang %></td>
			</tr>
			<tr>
				<th>Thanh toán</th>
				<td><%= @don_hang.thanh_toan %></td>
			</tr>
		</table>
		
		<table class="table table-bordered">
			<thead>
				<th>Tên hàng hóa</th>
				<th>Số lượng</th>
				<th>ĐVT</th>
				<th>Đơn giá</th>
				<th>Thành tiền</th>
			</thead>
			<% @don_hang.chi_tiet_gio_hangs.each do |chi_tiet| %>
			<tr>
				<td><%= chi_tiet.hang_hoa.ten_hang %></td>
				<td><%= chi_tiet.so_luong %></td>
				<td><%= chi_tiet.hang_hoa.dvt %></td>
				<td align="right"><%= number_to_currency(chi_tiet.gia_ban, locale: :vn) %></td>
				<td align="right"><%= number_to_currency(chi_tiet.tong_cong, locale: :vn) %></td>
			</tr>
			<% end %>
			<tr>
				<td colspan="4" align="right"><strong>TỔNG CỘNG</strong></td>
				<td align="right"><strong><%= number_to_currency(@don_hang.tong_cong, locale: :vn)%></strong></td>
			</tr>
		</table>
	</div>
</div>