config/routes.rb
Rails.application.routes.draw do

  resources :chi_tiet_gio_hangs
  resources :gio_hangs
  resources :don_hangs
  devise_for :views
  devise_for :khach_hangs
  
  root 'trang_chu#index', as: 'home'

  get '/store' => 'hang_hoas#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy' 

  namespace :admin do
    resources :thong_kes, only: [:index]
    resources :don_hangs
    resources :khach_hangs
    resources :hang_hoas
    resources :danh_mucs
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end

  resources :hang_hoas, only: [:index, :show]
  resources :danh_mucs, only: [:index, :show]

end

app/models/chi_tiet_gio_hang.rb
class ChiTietGioHang < ActiveRecord::Base
  belongs_to :hang_hoa
  belongs_to :gio_hang
  belongs_to :don_hang

  def gia_ban
  	hang_hoa.gias.last[:gia_ban]
  end

  def tong_cong
  	hang_hoa.gias.last[:gia_ban] * so_luong
  end
end

app/controllers/chi_tiet_gio_hangs_controller.rb
class ChiTietGioHangsController < ApplicationController
  include GioHangHienTai

  before_action :set_gio_hang, only: [:create, :edit, :update]
  before_action :set_chi_tiet_gio_hang, only: [:show, :edit, :update, :destroy]

  # GET /chi_tiet_gio_hangs
  # GET /chi_tiet_gio_hangs.json
  def index
    @chi_tiet_gio_hangs = ChiTietGioHang.all
  end

  # GET /chi_tiet_gio_hangs/1
  # GET /chi_tiet_gio_hangs/1.json
  def show
  end

  # GET /chi_tiet_gio_hangs/new
  def new
    @chi_tiet_gio_hang = ChiTietGioHang.new
  end

  # GET /chi_tiet_gio_hangs/1/edit
  def edit
    hang_hoa = HangHoa.find(params[:hang_hoa_id])
    so_luong = params[:so_luong]
    @gia = Gia.find(params[:hang_hoa_id])
    @chi_tiet_gio_hang = @gio_hang.them_hang_hoa(hang_hoa.id, so_luong)
  end

  # POST /chi_tiet_gio_hangs
  # POST /chi_tiet_gio_hangs.json
  def create
    hang_hoa = HangHoa.find(params[:hang_hoa_id])
    so_luong = params[:so_luong]
    @gia = Gia.find(params[:hang_hoa_id])
    @chi_tiet_gio_hang = @gio_hang.them_hang_hoa(hang_hoa.id, so_luong)

    respond_to do |format|
      if @chi_tiet_gio_hang.save
        format.html { redirect_to @chi_tiet_gio_hang.gio_hang, notice: 'Thêm vào giỏ hàng thành công' }
        format.json { render :show, status: :created, location: @chi_tiet_gio_hang }
      else
        format.html { render :new }
        format.json { render json: @chi_tiet_gio_hang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chi_tiet_gio_hangs/1
  # PATCH/PUT /chi_tiet_gio_hangs/1.json
  def update
    chi_tiet = ChiTietGioHang.find(params[:id])
    respond_to do |format|
      if @chi_tiet_gio_hang.update(update_chi_tiet_gio_hang_params)
        format.html { redirect_to :back, notice: 'Giỏ hàng đã được cập nhật' }
        format.json { render :show, status: :ok, location: @chi_tiet_gio_hang }
      else
        format.html { render :edit }
        format.json { render json: @chi_tiet_gio_hang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chi_tiet_gio_hangs/1
  # DELETE /chi_tiet_gio_hangs/1.json
  def destroy

    @chi_tiet_gio_hang.destroy
    respond_to do |format|
      format.html { redirect_to gio_hang_path(set_gio_hang), notice: 'Hàng hóa đã được xóa khỏi giỏ hàng' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chi_tiet_gio_hang
      @chi_tiet_gio_hang = ChiTietGioHang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chi_tiet_gio_hang_params
      params.require(:chi_tiet_gio_hang).permit(:hang_hoa_id, :so_luong)
    end

    def update_chi_tiet_gio_hang_params
      params.require(:chi_tiet_gio_hang).permit(:so_luong)
    end
end

app/helpers/chi_tiet_gio_hangs_helper.rb
module ChiTietGioHangsHelper
end

app/views/chi_tiet_gio_hangs/_chi_tiet_gio_hang.html.erb
<tr>
	<td><%= chi_tiet_gio_hang.so_luong %> &times;</td>
	<td><%= chi_tiet_gio_hang.hang_hoa.ten_hang %></td>
	<td><%= number_to_currency(chi_tiet_gio_hang.tong_cong, locale: :vn) %></td>
</tr>

app/views/chi_tiet_gio_hangs/_form.html.erb
<%= form_for(@chi_tiet_gio_hang) do |f| %>
  <% if @chi_tiet_gio_hang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chi_tiet_gio_hang.errors.count, "error") %> prohibited this chi_tiet_gio_hang from being saved:</h2>

      <ul>
      <% @chi_tiet_gio_hang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hang_hoa_id %><br>
    <%= f.text_field :hang_hoa_id %>
  </div>
  <div class="field">
    <%= f.label :gio_hang_id %><br>
    <%= f.text_field :gio_hang_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chi_tiet_gio_hangs/edit.html.erb
<h1>Editing Chi Tiet Gio Hang</h1>

<%= render 'form' %>

<%= link_to 'Show', @chi_tiet_gio_hang %> |
<%= link_to 'Back', chi_tiet_gio_hangs_path %>

app/views/chi_tiet_gio_hangs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chi Tiet Gio Hangs</h1>

<table>
  <thead>
    <tr>
      <th>Hang hoa</th>
      <th>Gio hang</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chi_tiet_gio_hangs.each do |chi_tiet_gio_hang| %>
      <tr>
        <td><%= chi_tiet_gio_hang.hang_hoa %></td>
        <td><%= chi_tiet_gio_hang.gio_hang %></td>
        <td><%= link_to 'Show', chi_tiet_gio_hang %></td>
        <td><%= link_to 'Edit', edit_chi_tiet_gio_hang_path(chi_tiet_gio_hang) %></td>
        <td><%= link_to 'Destroy', chi_tiet_gio_hang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chi tiet gio hang', new_chi_tiet_gio_hang_path %>

app/views/chi_tiet_gio_hangs/new.html.erb
<h1>New Chi Tiet Gio Hang</h1>

<%= render 'form' %>

<%= link_to 'Back', chi_tiet_gio_hangs_path %>

app/views/chi_tiet_gio_hangs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hang hoa:</strong>
  <%= @chi_tiet_gio_hang.hang_hoa %>
</p>

<p>
  <strong>Gio hang:</strong>
  <%= @chi_tiet_gio_hang.gio_hang %>
</p>

<%= link_to 'Edit', edit_chi_tiet_gio_hang_path(@chi_tiet_gio_hang) %> |
<%= link_to 'Back', chi_tiet_gio_hangs_path %>