config/routes.rb
Rails.application.routes.draw do

  resources :chi_tiet_gio_hangs
  resources :gio_hangs
  resources :don_hangs
  devise_for :views
  devise_for :khach_hangs
  
  root 'trang_chu#index', as: 'home'

  get '/store' => 'hang_hoas#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy' 

  namespace :admin do
    resources :thong_kes, only: [:index]
    resources :don_hangs
    resources :khach_hangs
    resources :hang_hoas
    resources :danh_mucs
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end

  resources :hang_hoas, only: [:index, :show]
  resources :danh_mucs, only: [:index, :show]

end

app/models/danh_muc.rb
class DanhMuc < ActiveRecord::Base
	has_many :hang_hoas

	validates :ten_danh_muc, presence: true

	def dang_su_dung?
		HangHoa.exists?(danh_muc_id: self.id)
	end
end

app/controllers/admin/danh_mucs_controller.rb
class Admin::DanhMucsController < Admin::ApplicationController

  def new
    @danh_muc = DanhMuc.new
    @danh_mucs = DanhMuc.all.order(id: :desc)
  end

  def create
    @danh_muc = DanhMuc.new(danh_muc_params)

    if @danh_muc.save
      redirect_to new_admin_danh_muc_url, notice: 'Thêm danh mục thành công'
    else
      flash[:alert] = 'Có lỗi khi thêm danh mục'
      render 'new'
    end
  end

  def edit
    @danh_muc = DanhMuc.find(params[:id])
  end

  def update
    @danh_muc = DanhMuc.find(params[:id])
    if @danh_muc.update(danh_muc_params)
      redirect_to new_admin_danh_muc_url, notice: 'Chỉnh sửa danh mục thành công'
    else
      flash[:alert] = 'Có lỗi khi sửa danh mục'
      render 'edit'
    end
  end

  def show
    @danh_muc = DanhMuc.find(params[:id])
    @hang_hoas = @danh_muc.hang_hoas
  end

  def destroy
    @danh_muc = DanhMuc.find(params[:id])
    @danh_muc.destroy

    redirect_to :back, notice: 'Đã xóa danh mục'
  end

  private

  def danh_muc_params
    params.require(:danh_muc).permit(:ten_danh_muc, :id)
  end
end

app/helpers/admin/danh_mucs_helper.rb
module Admin::DanhMucsHelper

	def create_deletable_button danh_muc 
		if danh_muc.dang_su_dung?
			link_to '#' do
				content_tag(:button, 'Xóa', class: 'btn btn-danger btn-sm disabled')
			end
		else
			link_to admin_danh_muc_path(danh_muc), method: :delete do
				content_tag(:button, 'Xóa', class: 'btn btn-danger btn-sm')
			end
		end
	end
end

app/views/admin/danh_mucs/_form.html.erb
 <%= form_for [:admin, @danh_muc] do |f| %>
	<p style="font-size: 1.5em; font-weight: 600">TẠO DANH MỤC</p>
	<%= f.text_field :ten_danh_muc, class: "form-control", placeholder: "Tên danh mục", style: "font-size: 1.2em; padding: 5px 10px; height:auto" %>
	<%= f.submit "Khởi tạo", class: "btn btn-success pull-right", style: "margin-top: 10px" %>
<% end %>

app/views/admin/danh_mucs/edit.html.erb
<div class="function-headline">
	<h1>Chỉnh sửa danh mục</h1>
</div>
<div class="col-md-4 row">
	<%= form_for [:admin, @danh_muc] do |f| %>
	<p><%= f.text_field :ten_danh_muc, class: "form-control", style: "font-size: 1.4em; padding: 5px 10px; height:auto" %></p>
	<p>
		<%= f.submit "Sửa tên danh mục", class: "btn btn-success pull-right", style: "margin-left: 5px" %>	
		<%= link_to 'Trở lại', new_admin_danh_muc_path, class: "btn btn-primary pull-right" %>
	</p>
	<% end %>
</div>

app/views/admin/danh_mucs/new.html.erb
<div class="function-headline">
	<h1>Danh mục hàng hóa</h1>
</div>
<div class="row">
	
	<div class="col-md-4">
		<%= render 'form' %>
	</div>
	<div class="col-md-8 show-table">	
		<table>
			<thead>
				<tr>
					<th>Tên danh mục</th>
					<th>Tình trạng</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @danh_mucs.each do |danh_muc| %>
				<tr>
					<td><%= danh_muc.ten_danh_muc %></td>
					<td><%= true_false_converter(danh_muc.dang_su_dung?, truthy: 'Đang dùng', falsey: 'Chưa dùng')  %></td>
					<td>
						<%= link_to edit_admin_danh_muc_path(danh_muc) do %>
						<button type="button" class="btn btn-warning btn-sm">Sửa</button>
						<% end %>
					</td>
					<td><%= create_deletable_button danh_muc %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/danh_mucs/show.html.erb
<div class="function-headline">
	<h1><%= @danh_muc.ten_danh_muc %></h1>
</div>
<div class="product-category-listing">
	<table class="hang-hoa-table" width="100%">
	<thead>
		<tr>
			<th>Mã hàng</th>
			<th>Tên hàng</th>
			<th>Số lượng</th>
			<th>ĐVT</th>
			<th>Xuất xứ</th>
			<th>Quy cách</th>
			<th>Ghi chú</th>
			<th>Gía bán</th>
		</tr>
	</thead>
	<tbody>
		<% @hang_hoas.each do |hang_hoa| %>
		<tr>
			<td align="center"><%= hang_hoa.ma_hang %></td>
			<td><%= hang_hoa.ten_hang %></td>
			<td align="center"><%= hang_hoa.so_luong %></td>
			<td align="center"><%= hang_hoa.dvt %></td>
			<td align="center"><%= hang_hoa.xuat_xu %></td>
			<td align="center"><%= hang_hoa.quy_cach %></td>
			<td><%= hang_hoa.ghi_chu %></td>
			<td>
				<select class="form-control">
					<% hang_hoa.gias.each do |gia| %>
					<option><%= gia.gia_ban %></option>
					<% end %>
				</select>
			</td>
			<td align="center"><%= link_to 'Xem', admin_hang_hoa_path(hang_hoa) %></td>
			<td align="center"><%= link_to 'Sửa', edit_admin_hang_hoa_path(hang_hoa) %></td>
			<td align="center"><%= link_to 'Xóa', admin_hang_hoa_path(hang_hoa), method: :delete, data: {confirm: 'Bạn chắc chắn chưa?'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>