config/routes.rb
Rails.application.routes.draw do

  resources :chi_tiet_gio_hangs
  resources :gio_hangs
  resources :don_hangs
  devise_for :views
  devise_for :khach_hangs
  
  root 'trang_chu#index', as: 'home'

  get '/store' => 'hang_hoas#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy' 

  namespace :admin do
    resources :thong_kes, only: [:index]
    resources :don_hangs
    resources :khach_hangs
    resources :hang_hoas
    resources :danh_mucs
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end

  resources :hang_hoas, only: [:index, :show]
  resources :danh_mucs, only: [:index, :show]

end

app/models/chi_tiet_gio_hang.rb
class ChiTietGioHang < ActiveRecord::Base
  belongs_to :hang_hoa
  belongs_to :gio_hang
  belongs_to :don_hang

  def gia_ban
  	hang_hoa.gias.last[:gia_ban]
  end

  def tong_cong
  	hang_hoa.gias.last[:gia_ban] * so_luong
  end
end

app/models/cthd_nhap.rb
class CthdNhap < ActiveRecord::Base
  belongs_to :hoa_don_nhap
  
  has_many :hang_hoas
end

app/models/cthd_xuat.rb
class CthdXuat < ActiveRecord::Base
  belongs_to :hoa_don_xuat

  has_many :hang_hoas
end

app/models/danh_muc.rb
class DanhMuc < ActiveRecord::Base
	has_many :hang_hoas

	validates :ten_danh_muc, presence: true

	def dang_su_dung?
		HangHoa.exists?(danh_muc_id: self.id)
	end
end

app/models/don_hang.rb
class DonHang < ActiveRecord::Base

	belongs_to :khach_hang
	
	before_create :tong_cong, unless: :persisted?
	after_initialize :set_defaults, unless: :persisted?
	has_many :chi_tiet_gio_hangs, dependent: :destroy

	KIEU_THANH_TOAN = ["Chuyển khoản", "Thanh toán tại cửa hàng", "Thanh toán khi nhận hàng"]
	TINH_TRANG = [ "Đã tiếp nhận", "Đang xử lý", "Đã chuẩn bị xong", "Đang giao hàng", "Giao hàng thành công" ]

	validates :nguoi_nhan, :dia_chi, :email, presence: true
	validates :kieu_thanh_toan, inclusion: KIEU_THANH_TOAN

	def set_defaults
		self.tinh_trang ||= 'Đã tiếp nhận'
	end

	def them_chi_tiet_tu_gio_hang(gio_hang)
		gio_hang.chi_tiet_gio_hangs.each do |item|
			item.gio_hang_id = nil
			chi_tiet_gio_hangs << item
		end
	end

	def tong_cong
		self.tong_cong = chi_tiet_gio_hangs.to_a.sum {|chi_tiet| chi_tiet.tong_cong}
	end

	def self.doanh_thu_thang
		@don_hangs = DonHang.where('tinh_trang LIKE ?', 'Giao hàng thành công').group('month(updated_at)').order('updated_at desc')
		@doanh_thu_thang = @don_hangs.sum('tong_cong')
	end

	def self.doanh_thu_nam
		@don_hangs = DonHang.select('year(updated_at)').where('tinh_trang LIKE ?', 'Giao hàng thành công').group('year(updated_at)')
		@doanh_thu_nam = @don_hangs.sum('tong_cong')
	end

end

app/models/gia.rb
class Gia < ActiveRecord::Base
  belongs_to :hang_hoa

  validates :gia_ban, presence: true
end

app/models/gio_hang.rb
class GioHang < ActiveRecord::Base
	has_many :chi_tiet_gio_hangs, dependent: :destroy

	def them_hang_hoa(hang_hoa_id, so_luong)
		current_item = chi_tiet_gio_hangs.find_by(hang_hoa_id: hang_hoa_id)
		if current_item
			current_item.so_luong += so_luong.to_i
		else
			current_item = chi_tiet_gio_hangs.build(hang_hoa_id: hang_hoa_id)
			current_item.so_luong += so_luong.to_i - 1
		end
		current_item
	end


	def tong_cong
		chi_tiet_gio_hangs.to_a.sum {|chi_tiet| chi_tiet.tong_cong}
	end

end

app/models/hang_hoa.rb
class HangHoa < ActiveRecord::Base

	before_destroy :ensure_not_referenced_by_any_line_item


	has_attached_file 	:image,
						 styles: { large: "500x500>", medium: "300x300>", thumb: "183x183>", xs: "120x120>"},
						 default_url: "/images/:style/missing.png"

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	validates :ten_hang, presence: true
	validates :so_luong, presence: true
	validates :dvt, presence:true

	belongs_to :moderator
	belongs_to :danh_muc

	has_many :gias, dependent: :destroy
	has_many :chi_tiet_gio_hangs
	has_many :don_hangs, through: :chi_tiet_gio_hangs

	accepts_nested_attributes_for 	:gias,
									allow_destroy: true,
									reject_if: proc { |att| att['gia_ban'].blank? }

	def self.tim_kiem search
		where("ten_hang LIKE ? OR xuat_xu LIKE ?", "%#{search}%", "%#{search}%")
	end

	private 
		def ensure_not_referenced_by_any_line_item
			if chi_tiet_gio_hangs.empty?
				return true
			else
				errors.add(:base, 'Tồn tại chi tiết giỏ hàng!')
				return false
			end
		end
end

app/models/hoa_don_nhap.rb
class HoaDonNhap < ActiveRecord::Base
  belongs_to :nha_cung_cap

  has_many :cthd_nhaps
end

app/models/hoa_don_xuat.rb
class HoaDonXuat < ActiveRecord::Base
  belongs_to :khach_hang

  has_many :cthd_xuats
end

app/models/khach_hang.rb
class KhachHang < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  	has_many :don_hangs
  	
  	devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

    accepts_nested_attributes_for 	:don_hangs,
									allow_destroy: true

	def self.top_khach_hang
		KhachHang.joins(:don_hangs)
				.select('SUM(tong_cong) as total', 'khach_hangs.id', 'khach_hangs.email', 'khach_hangs.ten_kh')
				.where("don_hangs.tinh_trang like ?", "Giao hàng thành công")
				.group(:email)
				.order('total desc')
				.limit(10)
	end
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
	has_secure_password

	has_many :hang_hoas

	validates :fullname, presence: true
	validates :username, presence: true, format: { with: /@/, message: 'is not valid' }
	validates :password, presence: true
end

app/models/nha_cung_cap.rb
class NhaCungCap < ActiveRecord::Base
end

app/models/thong_ke.rb
class ThongKe < ActiveRecord::Base

	def last_value
		values.last
	end

end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/don_hangs_controller.rb
class DonHangsController < ApplicationController

	include GioHangHienTai
	before_action :set_gio_hang, only: [:index, :show, :new, :create]
	before_action :set_don_hang, only: [:show, :edit, :update, :destroy]

	def index
		@don_hangs = current_khach_hang.don_hangs
	end

	def show
	end

	def edit
	end

	def new
		if @gio_hang.chi_tiet_gio_hangs.empty?
			redirect_to store_url, notice: "Giỏ hàng của bạn chưa có sản phẩm nào"
			return
		end
		@khach_hang = current_khach_hang
		@don_hang = DonHang.new

	end


	def create
		@don_hang = DonHang.new(don_hang_params)
		@don_hang.them_chi_tiet_tu_gio_hang(@gio_hang)
		@don_hang.khach_hang_id = current_khach_hang.id
		@khach_hang = current_khach_hang

		if @don_hang.save
			GioHang.destroy(session[:gio_hang_id])
			session[:gio_hang_id] = nil
			redirect_to don_hang_url(@don_hang), notice: "Bạn đã đặt hàng thành công!"
		else
	        flash[:alert] = "Hãy điền thông tin đầy để chúng tôi có thể xử lý đơn hàng"
			render 'new'
      	end

	end

	private

	def set_don_hang
		@don_hang = DonHang.find(params[:id])
	end

	def don_hang_params
		params.require(:don_hang).permit(:nguoi_nhan, :dia_chi, :email, :tinh_trang, :thanh_toan, :kieu_thanh_toan)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def true_false_converter(status, truthy: 'Active', falsey: 'Disabled')
		if status
			truthy
		else
			falsey
		end
	end
end

app/helpers/gio_hangs_helper.rb
module GioHangsHelper
end

app/helpers/hang_hoas_helper.rb
module HangHoasHelper
end

app/helpers/trang_chu_helper.rb
module TrangChuHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BL - Quản Lý</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900" rel="stylesheet' %>
		<%= csrf_meta_tags %>
	</head>
	<body class="admin-body">
		<div class="container-fluid dashboard-wrapper">
			<div class="row">
				<div class="col-md-2">
					<div class="sidebar affix row">
						<div class="dashboard-store-logo"><%= image_tag 'BL-White-Logo.png', width: "30%"%></div>
						<div class="dashboard-menu">
							<ul>
								<%= link_to admin_thong_kes_path do %>
								<li>
									<i class="fa fa-bar-chart" aria-hidden="true"></i>
									<p>Thống kê</p>
									<% end %>
								<%= link_to admin_hang_hoas_path do %>
								<li>
									<i class="fa fa-home" aria-hidden="true"></i>
									<p>Kho hàng</p>
									<% end %>
									<%= link_to new_admin_danh_muc_path do %>
									<li>
										<i class="fa fa-list" aria-hidden="true"></i>
										<p>Danh mục hàng</p>
									</li>
									<% end %>
									<%= link_to admin_moderators_path do %>
									<li>
										<i class="fa fa-user-secret" aria-hidden="true"></i>
										<p>Quản trị viên</p>
									</li>
									<% end %>
									<%= link_to admin_don_hangs_path do %>
									<li>
										<i class="fa fa-file-text" aria-hidden="true"></i>
										<p>Đơn hàng</p>
									</li>
									<% end %>
									<%= link_to admin_khach_hangs_path do %>
									<li>
										<i class="fa fa-user" aria-hidden="true"></i>
										<p>Khách hàng</p>
									</li>
									<% end %>
								</ul>
							</div>
						</div>
					</div>
					
					
					
					<div class="col-md-10">
						<div class="main-board">
							<div class="dashboard-navbar navbar row">
								<div class="container-fluid">
									<!-- <div class="navbar-header">
																<button type="button" class="navbar-toggle collapsed" dât-toggle="collapse" dât-target="#navbar-collapse-items" ẩi-expanded="false">
																<span class="sr-only">Toggle navigation</span>
																<span class="icon-bả"></span>
																<span class="icon-bả"></span>
																<span class="icon-bả"></span>
																</button>
																<h3>Tổng quan</h3>
									</div> -->
									<div class="col-md-4">
										<% if flash[:notice] %>
										<div class="alert alert-info"><%= flash[:notice] %></div>
										<% end %>
										<% if flash[:alert] %>
										<div class="alert alert-warning"><%= flash[:alert] %></div>
										<% end %>
									</div>
									<div class="navbar-collapse collapse" id="navbar-collapse-items">
										<ul class="nav navbar-nav navbar-right">
											<li><a href="#"><i class="fa fa-bell" aria-hidden="true"></i></a></li>
											<li class="dropdown">
												<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Kỳ Anh <i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
												<ul class="dropdown-menu">
													<li><a href="#">Action</a></li>
													<li><a href="#">Another action</a></li>
													<li><a href="#">Something else here</a></li>
													<li role="separator" class="divider"></li>
													<li><a href="#">Separated link</a></li>
												</ul>
											</li>
											<li><%= link_to 'Đăng xuất', logout_path %> <br></li>
										</ul>
									</div>
								</div>
								<div class="dashboard-content">
									<%= yield %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</body>
		</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BL Store</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900" rel="stylesheet' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body class="application-body">
		<nav class="navbar">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-items" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">
						<%= image_tag 'Logo.png', width: "60px", id: "logo-img" %>
					</a>
				</div>
				<div class="upperline-nav">
					<i class="fa fa-phone"></i><span class="contact-number">0914 0924 77 - 0918 259 412</span>
					<span>
						<% if khach_hang_signed_in? %>
						<div class="dropdown" style="display: inline-block">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-circle"></i> Chào <strong><%= current_khach_hang.ten_kh.partition(' ').last %></strong> <i class="fa fa-caret-down" aria-hidden="true"></i></a>
							<ul class="dropdown-menu pull-right">
								<li><%= link_to 'Thông tin tài khoản', edit_khach_hang_registration_path %></li>

								<li><%= link_to 'Quản lý đơn hàng', don_hangs_path %></li>
								<li role="separator" class="divider"></li>
								<li>
									<%= link_to destroy_khach_hang_session_path, method: :delete do %>
									Thoát tài khoản</i>
									<% end %>
								</li>
							</ul>
						</div>
							
						<% else %>
						<span class="sign-in-up">
							<%= link_to 'Đăng ký', new_khach_hang_registration_path %><span class="separate-line">|</span>
							<%= link_to new_khach_hang_session_path do %>
								Đăng nhập <i class="fa fa-sign-in"></i>
							<% end %>
						</span>
						<% end %>
					</span>
				</div>
				<div class="navbar-collapse collapse" id="navbar-collapse-items">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="/">Trang chủ</a></li>
						<li><a href="/store">Cửa hàng</a></li>
						<li><a href="#">Liên hệ</a></li>
						<li id="shopping-cart">
							<%= link_to gio_hang_path(@gio_hang) do %>
								<i class="fa fa-shopping-cart"></i> Giỏ hàng
							<% end %>
						</li>

					</ul>
				</div>
			</div>
		</nav>
<!-- 		<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
		<% end %>
		<% if flash[:alert] %>
		<div class="alert"><%= flash[:alert] %></div>
		<% end %> -->
		<%= yield %>
	</body>
	<footer class="footer-section row">
			<div class="container">
				<div class="logo-footer col-md-1">
					<%= image_tag 'BL-White-Logo.png', width: "60px", id: "logo-img" %>
				</div>
				<div id="store-name" class="col-md-4">
					<h3>Cửa hàng thiết bị lạnh công nghiệp <span style="font-weight: 600">BL</span></h3>
					<h4>© 2017 - BLStore</h4>
				</div>
				<div id="store-info" class="pull-right col-md-4">
					<h3>37 Trịnh Phong, Nha Trang, Khánh Hòa</h3>
					<h3><span style="font-weight: 600"> HOTLINE: </span><span style="font-weight:400">0914 0924 77 - 0918 259 501</span></h3>
					<h3>Email: <a href="baylocnt@gmail.com?subject=feedback" "email me">baylocnt@gmail.com</a></h3>
				</div>
			</div>
			
		</footer>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BL Store</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900" rel="stylesheet' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body class="application-body">
		<nav class="navbar">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-items" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">
						<%= image_tag 'Logo.png', width: "60px", id: "logo-img" %>
					</a>
				</div>
				<div class="upperline-nav">
					<i class="fa fa-phone"></i>  <span>0914 0924 77 - 0918 259 412</span>
					<span>
						<% if khach_hang_signed_in? %>
						<div class="dropdown" style="display: inline-block">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-circle"></i> Chào <strong><%= current_khach_hang.ten_kh.partition(' ').last %></strong> <i class="fa fa-caret-down" aria-hidden="true"></i></span></a>
							<ul class="dropdown-menu pull-right">
								<li><%= link_to 'Thông tin tài khoản', edit_khach_hang_registration_path %></li>
								<li><%= link_to 'Quản lý đơn hàng', don_hangs_path %></li>
								<li role="separator" class="divider"></li>
								<li>
									<%= link_to destroy_khach_hang_session_path, method: :delete do %>
									Thoát tài khoản</i>
									<% end %>
								</li>
							</ul>
						</div>
						<% else %>
						<span class="sign-in-up">
						<%= link_to 'Đăng ký', new_khach_hang_registration_path %> |
						<%= link_to new_khach_hang_session_path do %>
						Đăng nhập <i class="fa fa-sign-in"></i>
						<% end %>
						</span>
						<% end %>
					</span>
				</div>
				<div class="navbar-collapse collapse" id="navbar-collapse-items">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="/">Trang chủ</a></li>
						<li><a href="/store">Cửa hàng</a></li>
						<li><a href="#">Liên hệ</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- 		<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
		<% end %>
		<% if flash[:alert] %>
		<div class="alert"><%= flash[:alert] %></div>
		<% end %> -->
		<div class="margin-btm">
			<%= yield %>
		</div>
	</body>
	<footer class="footer-section row">
		<div class="container">
			<div class="logo-footer col-md-1">
				<%= image_tag 'BL-White-Logo.png', width: "60px", id: "logo-img" %>
			</div>
			<div id="store-name" class="col-md-4">
				<h3>Cửa hàng thiết bị lạnh công nghiệp <span style="font-weight: 600">BL</span></h3>
				<h4>© 2017 - BLStore</h4>
			</div>
			<div id="store-info" class="pull-right col-md-4">
				<h3>37 Trịnh Phong, Nha Trang, Khánh Hòa</h3>
				<h3><span style="font-weight: 600"> HOTLINE: </span><span style="font-weight:400">0914 0924 77 - 0918 259 501</span></h3>
				<h3>Email: <a href="baylocnt@gmail.com?subject=feedback" "email me">baylocnt@gmail.com</a></h3>
			</div>
		</div>
		
	</footer>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900" rel="stylesheet' %>
  <%= csrf_meta_tags %>
</head>
<body class="login-body">

<div class="login-wrapper col-md-3">
	<%= yield %>	
</div>
</body>
</html>

app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>BL Store</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,900" rel="stylesheet' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body class="application-body">
		<nav class="navbar">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-items" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">
						<%= image_tag 'Logo.png', width: "60px", id: "logo-img" %>
					</a>
				</div>
				<div class="upperline-nav">
					<i class="fa fa-phone"></i><span class="contact-number">0914 0924 77 - 0918 259 412</span>
					<span>
						<% if khach_hang_signed_in? %>
						<div class="dropdown" style="display: inline-block">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-circle"></i> Chào <strong><%= current_khach_hang.ten_kh.partition(' ').last %></strong> <i class="fa fa-caret-down" aria-hidden="true"></i></a>
							<ul class="dropdown-menu pull-right">
								<li><%= link_to 'Thông tin tài khoản', edit_khach_hang_registration_path %></li>
								<li><%= link_to 'Quản lý đơn hàng', don_hangs_path %></li>
								<li role="separator" class="divider"></li>
								<li>
									<%= link_to destroy_khach_hang_session_path, method: :delete do %>
									Thoát tài khoản</i>
									<% end %>
								</li>
							</ul>
						</div>
						<% else %>
						<span class="sign-in-up">
							<%= link_to 'Đăng ký', new_khach_hang_registration_path %> |
							<%= link_to new_khach_hang_session_path do %>
							Đăng nhập <i class="fa fa-sign-in"></i>
							<% end %>
						</span>
						<% end %>
					</span>
				</div>
				<div class="navbar-collapse collapse" id="navbar-collapse-items">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="/">Trang chủ</a></li>
						<li><a href="/store">Cửa hàng</a></li>
						<li><a href="#">Liên hệ</a></li>
						<!-- <li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Giỏ hàng <%= fa_icon "shopping-cart" %><span id="product-in-cart">7</span></a>
									<ul class="dropdown-menu">
												<li><a href="#">Action</a></li>
												<li><a href="#">Another action</a></li>
												<li><a href="#">Something else here</a></li>
												<li role="separator" class="divider"></li>
												<li><a href="#">Separated link</a></li>
									</ul>
						</li> -->
						<li id="shopping-cart">
							<%= link_to gio_hang_path(@gio_hang) do %>
							<i class="fa fa-shopping-cart"></i> Giỏ hàng
							<% end %>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="search-bar-section container margin-btm">
			<div class="col-md-12">
				<div class="search-bar col-md-5">
					<%= form_tag(hang_hoas_path, method: :get) do %>
					<div class="input-group">
						<%= text_field_tag :search, "", class: "form-control", placeholder: "Tìm kiếm" %>
						<span class="input-group-btn" id="search-btn">
							<%= button_tag type: 'submit', class: "btn btn-primary" do %>
							<i class="fa fa-search" aria-hidden="true"></i>
							<% end %>
						</span>
					</div>
					<% end %>
				</div>
			</div>
		</div>
		<div class="container">
			<% if flash[:notice] %>
			<div class="alert alert-success"><%= flash[:notice] %></div>
			<% end %>
			<% if flash[:alert] %>
			<div class="alert alert-danger"><%= flash[:alert] %></div>
			<% end %>
		</div>
		<div class="margin-btm">
			<%= yield %>
		</div>
	</body>
	<footer class="footer-section row">
		<div class="container">
			<div class="logo-footer col-md-1">
				<%= image_tag 'BL-White-Logo.png', width: "60px", id: "logo-img" %>
			</div>
			<div id="store-name" class="col-md-4">
				<h3>Cửa hàng thiết bị lạnh công nghiệp <span style="font-weight: 600">BL</span></h3>
				<h4>© 2017 - BLStore</h4>
			</div>
			<div id="store-info" class="pull-right col-md-4">
				<h3>37 Trịnh Phong, Nha Trang, Khánh Hòa</h3>
				<h3><span style="font-weight: 600"> HOTLINE: </span><span style="font-weight:400">0914 0924 77 - 0918 259 501</span></h3>
				<h3>Email: <a href="baylocnt@gmail.com?subject=feedback" "email me">baylocnt@gmail.com</a></h3>
			</div>
		</div>
		
	</footer>
</html>